=== luongmanh1603/T2210A_XML/student.dtd
<!ELEMENT student (name,age,(tel|mobile),address, class)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT class (name,room)>
<!ELEMENT room (#PCDATA)>

=== luongmanh1603/T2210A_XML/demo.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE student SYSTEM "./student.dtd"> -->
<!--<?xml-stylesheet href="student.css" type="text/css"?> -->
<?xml-stylesheet href="student.xslt" type="text/css"?>
<student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./student.xsd">
    <name>Nguyen Van An</name>
    <age>18</age>
    <tel>0987654323</tel>
    <address>8A Ton That Thuyet</address>
    <class>
        <name>T2210A</name>
        <room>B10</room>
    </class>
</student>
